name: Enso
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  path_provider: ^2.1.1
  share_plus: ^11.0.0
  pdf: ^3.10.4
  printing: ^5.12.0
  intl: ^0.20.2
  open_file: ^3.3.2
  url_launcher: ^6.1.14
  http: ^1.2.1
  flutter_local_notifications: ^18.0.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.0+1
  audioplayers: ^6.4.0
  percent_indicator: ^4.2.3
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  flutter_plugin_android_lifecycle: ^2.0.28
  external_path: ^2.2.0

  shared_preferences: ^2.2.2
  mailer: ^6.0.1
  signature: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/fond.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
